### ISSUE TITLE
Not Working on Ubuntu 12.04

### ISSUE THREAD

**Issue by rdegges** [heroku/heroku-pg-extras#47]
Hey all,

I'm trying to get pg-extras working, but am having issues. Here's what I get after installing the plugin successfully, and attempting to run cache_hit:

``` bash
$ heroku pg:cache_hit                                                

 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined local variable or method `find_uri' for #<Heroku::Command::Pg:0x000000029818c0> (NameError)
    Backtrace:   /home/rdegges/.heroku/plugins/heroku-pg-extras/init.rb:464:in `exec_sql'
                 /home/rdegges/.heroku/plugins/heroku-pg-extras/init.rb:25:in `cache_hit'
                 /home/rdegges/.rvm/gems/ruby-1.9.3-p374/gems/heroku-2.39.3/lib/heroku/command.rb:206:in `run'
                 /home/rdegges/.rvm/gems/ruby-1.9.3-p374/gems/heroku-2.39.3/lib/heroku/cli.rb:28:in `start'
                 /home/rdegges/.rvm/gems/ruby-1.9.3-p374/gems/heroku-2.39.3/bin/heroku:17:in `<top (required)>'
                 /home/rdegges/.rvm/gems/ruby-1.9.3-p374/bin/heroku:19:in `load'
                 /home/rdegges/.rvm/gems/ruby-1.9.3-p374/bin/heroku:19:in `<main>'
                 /home/rdegges/.rvm/gems/ruby-1.9.3-p374/bin/ruby_noexec_wrapper:14:in `eval'
                 /home/rdegges/.rvm/gems/ruby-1.9.3-p374/bin/ruby_noexec_wrapper:14:in `<main>'

    Command:     heroku pg:cache_hit
    Plugins:     heroku-accounts
                 heroku-config
                 heroku-pg-extras
                 heroku-production-check
                 heroku.json

    Version:     heroku-gem/2.39.3 (x86_64-linux) ruby/1.9.3
```
